# Generated by Django 2.1 on 2018-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XGbAnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uen', models.CharField(blank=True, db_column='UEN', max_length=50, null=True)),
                ('recommendedproduct', models.CharField(blank=True, db_column='RecommendedProduct', max_length=500, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xgbresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uen', models.CharField(blank=True, db_column='UEN', max_length=50, null=True)),
                ('recommendedproduct', models.CharField(blank=True, db_column='RecommendedProduct', max_length=500, null=True)),
                ('application_defense', models.FloatField(blank=True, db_column='Application Defense', null=True)),
                ('cloud_security', models.FloatField(blank=True, db_column='Cloud Security', null=True)),
                ('consulting_services', models.FloatField(blank=True, db_column='Consulting Services', null=True)),
                ('content_defense', models.FloatField(blank=True, db_column='Content Defense', null=True)),
                ('csi', models.FloatField(blank=True, db_column='CSI', null=True)),
                ('data_centre_security', models.FloatField(blank=True, db_column='Data Centre Security', null=True)),
                ('endpoint_defense', models.FloatField(blank=True, db_column='Endpoint Defense', null=True)),
                ('endpoint_security', models.FloatField(blank=True, db_column='Endpoint Security', null=True)),
                ('mss_others', models.FloatField(blank=True, db_column='MSS Others', null=True)),
                ('network_defense', models.FloatField(blank=True, db_column='Network Defense', null=True)),
                ('operational_technology_security', models.FloatField(blank=True, db_column='Operational Technology Security', null=True)),
                ('ot_security', models.FloatField(blank=True, db_column='OT Security', null=True)),
                ('ps_others', models.FloatField(blank=True, db_column='PS Others', null=True)),
                ('ps_others_bespoke_field', models.FloatField(blank=True, db_column='PS Others (Bespoke)', null=True)),
                ('soc_services', models.FloatField(blank=True, db_column='SOC Services', null=True)),
                ('ts_others', models.FloatField(blank=True, db_column='TS Others', null=True)),
                ('ts_others_bespoke_field', models.FloatField(blank=True, db_column='TS Others (Bespoke)', null=True)),
            ],
            options={
                'db_table': 'XGBresult',
                'managed': True,
            },
        ),
    ]
