# Generated by Django 2.1 on 2018-10-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20181030_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(blank=True, db_column='Name', max_length=500, null=True)),
                ('uen', models.CharField(db_column='UEN', max_length=50, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=500, null=True)),
                ('cfu', models.CharField(blank=True, db_column='CFU', max_length=500, null=True)),
                ('genericindustry', models.CharField(blank=True, db_column='GenericIndustry', max_length=500, null=True)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=500, null=True)),
                ('acsaccountstatus', models.CharField(blank=True, db_column='ACSAccountStatus', max_length=500, null=True)),
                ('acscreditrating', models.SmallIntegerField(blank=True, db_column='ACSCreditRating', null=True)),
                ('acrastatus', models.CharField(blank=True, db_column='ACRAStatus', max_length=500, null=True)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=500, null=True)),
                ('parentcompany', models.CharField(blank=True, db_column='ParentCompany', max_length=500, null=True)),
                ('companygroup', models.CharField(blank=True, db_column='CompanyGroup', max_length=500, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='xgbresult',
            options={'managed': False},
        ),
    ]
