# Generated by Django 2.1 on 2018-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsServices',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=100, primary_key=True, serialize=False)),
                ('financiall1', models.CharField(blank=True, db_column='FinancialL1', max_length=500, null=True)),
                ('financiall2', models.CharField(blank=True, db_column='FinancialL2', max_length=500, null=True)),
                ('financiall3', models.CharField(blank=True, db_column='FinancialL3', max_length=500, null=True)),
                ('productmanagement', models.CharField(blank=True, db_column='ProductManagement', max_length=50, null=True)),
                ('devicemanagementandmonitoring', models.CharField(blank=True, db_column='DeviceManagementAndMonitoring', max_length=10, null=True)),
                ('threatanalysis', models.CharField(blank=True, db_column='ThreatAnalysis', max_length=10, null=True)),
                ('threatdetection', models.CharField(blank=True, db_column='ThreatDetection', max_length=10, null=True)),
                ('threatresponse', models.CharField(blank=True, db_column='ThreatResponse', max_length=10, null=True)),
                ('threatintelligence', models.CharField(blank=True, db_column='ThreatIntelligence', max_length=10, null=True)),
                ('identify', models.CharField(blank=True, db_column='Identify', max_length=10, null=True)),
                ('protect', models.CharField(blank=True, db_column='Protect', max_length=10, null=True)),
                ('cost', models.FloatField(blank=True, db_column='Cost', null=True)),
            ],
            options={
                'db_table': 'Products/Services',
                'managed': False,
            },
        ),
    ]
