# Generated by Django 2.1 on 2018-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_productsservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArFeatureResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, db_column='Rule', max_length=4000, null=True)),
                ('support', models.FloatField(blank=True, db_column='Support', null=True)),
                ('confidence', models.FloatField(blank=True, db_column='Confidence', null=True)),
                ('lift', models.FloatField(blank=True, db_column='Lift', null=True)),
            ],
            options={
                'db_table': 'AR_Feature_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArProductResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, db_column='Rule', max_length=4000, null=True)),
                ('support', models.FloatField(blank=True, db_column='Support', null=True)),
                ('confidence', models.FloatField(blank=True, db_column='Confidence', null=True)),
                ('lift', models.FloatField(blank=True, db_column='Lift', null=True)),
            ],
            options={
                'db_table': 'AR_Product_result',
                'managed': True,
            },
        ),
    ]
