# Generated by Django 2.1 on 2018-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dealno', models.CharField(blank=True, db_column='DealNo', max_length=50, null=True)),
                ('dealtype', models.CharField(blank=True, db_column='DealType', max_length=50, null=True)),
                ('tcv_sgd_field', models.FloatField(blank=True, db_column='TCV(SGD)', null=True)),
                ('otc_sgd_field', models.FloatField(blank=True, db_column='OTC(SGD)', null=True)),
                ('mrc_sgd_field', models.FloatField(blank=True, db_column='MRC(SGD)', null=True)),
                ('contractperiod_months_field', models.SmallIntegerField(blank=True, db_column='ContractPeriod(Months)', null=True)),
                ('probability', models.FloatField(blank=True, db_column='Probability', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'Deals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DealsProducts',
            fields=[
                ('matchingid', models.AutoField(db_column='MatchingID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Deals~Products',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='history',
            name='dealtype',
        ),
        migrations.AddField(
            model_name='history',
            name='deal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='deal_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='contractperiod_months_field',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='mrc_sgd_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='otc_sgd_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='tcv_sgd_field',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
