# Generated by Django 2.1 on 2018-11-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181102_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
