# Generated by Django 2.1 on 2018-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('UEN', models.IntegerField()),
                ('Sector', models.CharField(max_length=250)),
                ('CFU', models.CharField(max_length=250)),
                ('GenericIndustry', models.CharField(max_length=250)),
                ('Industry', models.CharField(max_length=250)),
                ('ACSAccountStatus', models.CharField(max_length=250)),
                ('ACSCreditRating', models.IntegerField(default=0)),
                ('ACRAStatus', models.CharField(max_length=250)),
                ('Group', models.CharField(max_length=250)),
                ('ParentCompany', models.CharField(max_length=250)),
                ('CompanyGroup', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
    ]
